services:
  nextjs-app-mama:
    build:
      context: .
      dockerfile: Dockerfile.dev
      # dockerfile: Dockerfile
    restart: always
    env_file:
      - .env.nodejs
    ports:
      - "8921:3000"
    networks:
      - marijan-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextjs.rule=Host(`kezar.at`)"
      - "traefik.http.routers.nextjs.entrypoints=websecure"
      - "traefik.http.routers.nextjs.tls=true"
      - "traefik.http.routers.nextjs.tls.certresolver=mytls"
      - "traefik.http.services.nextjs.loadbalancer.server.port=3000"

networks:
  marijan-network:
    external: true
