# services:
#   app:
#     image: marijan-projekt_app
#     volumes:
#       - ./:/usr/src/app
#     ports:
#       - "4000:4000"



services:
  postgres:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: marijan
      POSTGRES_PASSWORD: marijan008
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "marijan"]
      interval: 10s
      retries: 5
      start_period: 5s
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    networks:
      - marijan-network

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    ports:
      - "8900:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: noreply-be70d@mahle.com
      PGADMIN_DEFAULT_PASSWORD: marijan008
    networks:
      - marijan-network

  react-app:
    build: .
    restart: always
    ports:
      - "8901:4000"
    env_file:
      - .env
#    healthcheck:
#      test: curl --fail http://localhost:3000/api/healthcheck/
#      start_period: 30s
#      interval: 60s
#      timeout: 10s
#      retries: 3
    networks:
      - marijan-network


networks:
  marijan-network:
    name: marijan_network
    attachable: true
